### ISSUE TITLE
[ORIGIN-PROPOSAL] Drowned

### ISSUE THREAD

**Issue by Djtpj** [Djtpj/Spigot-Origins#7]
**Origin Info**
Name: Drowned
Description: The undead reincarnation of a sailor lost at sea.
Impact: Medium

**Origin Inspiration**
The mob from the base game.

**Origin Traits**
- [x] Photosensitive
- [x] Sea Born: Has Conduit Power
- [x] Pescetarian: Can only eat fish and vegetables
- [x] Trident Handy: Deals extra damage with a trident

**Comment by atticuscornett** [comment]
hi
